use_frameworks!

target 'NXLibFramework_Example' do
  pod 'NXLibFramework', :path => '../'

  target 'NXLibFramework_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
  pod 'FBSnapshotTestCase'
  end
end
